import pytest
from day8.solution import a_frequency, t_frequency

@pytest.fixture
def input_data():
    return """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

def test_a_frequency(input_data):
    assert a_frequency(input_data) == 14

def test_t_frequency(input_data):
    assert t_frequency(input_data) == 34

